name: Ready API Testing POC

on:
    workflow_dispatch:
      inputs:
        env:
          description: Which env to run tests against?
          required: true
          type: choice
          default: test
          options:
            - dev
            - test
        ready_api_args:
          description: Additional args to pass to Ready API
          required: false
          type: string

jobs:
    run_ready_api_test:
        runs-on: codebuild-foo-${{ github.run_id }}-${{ github.run_attempt }}
        steps:
            - name: Clone repo
              uses: actions/checkout@v4
            - name: Hello
              run: echo HelloWorld
